default: &default
  adapter: postgresql
  encoding: unicode
  pool: 2
  variables:
    statement_timeout: 30000

local_default: &local_default
  <<: *default
  username: <%= ENV["DATABASE_USER"] || "root" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "root" %>
  host: <%= ENV["DATABASE_HOST"] || "localhost" %>
  port: <%= ENV["DATABASE_PORT"] || "5432" %>

development:
  <<: *local_default
  database: tipjar_server_development

test:
  <<: *local_default
  database: tipjar_server_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
