version: '3'

services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'root'

volumes:
  db-data:
    external: false